- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a managed Azure Container Services (AKS) instance
      azure_rm_aks:
         name: aksgbbready222
         location: westus
         resource_group: gbbready222
         dns_prefix: gbbready222
         linux_profile:
           admin_username: gbbdemo
           ssh_key: "REPLACE"
         service_principal:
           client_id: "SPAPPID"
           client_secret: "SPPASSWORD"
         agent_pool_profiles:
           - name: default
             count: 3
             vm_size: Standard_D2_v2
         tags:
           Environment: Production
